apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yz4mpbcrn-dotnet-basic 
  janus-idp.io/tekton: yz4mpbcrn-dotnet-basic
  backstage.io/kubernetes-id: yz4mpbcrn-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yz4mpbcrn-dotnet-basic
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml